### ISSUE TITLE
Error after starting bot

### ISSUE THREAD

**Issue by lerdem** [simplebot-org/simplebot_feeds#13]
After running 
```bash
simplebot --account not_real@mail.com serve
2021-10-10 13:42:45,616 - simplebot - INFO - bot listening at: not_real@mail.com
Illegal instruction
```
What is "Illegal instruction"?  Why after this serve command is interrupted?

Environment details:
```bash
$ python -V
Python 3.7.3
$ pip freeze
beautifulsoup4==4.10.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
deltachat==1.61.0
feedparser==6.0.8
html5lib==1.1
idna==3.3
IMAPClient==2.2.0
importlib-metadata==4.8.2
Jinja2==3.0.3
MarkupSafe==2.0.1
Pillow==8.4.0
pkg_resources==0.0.0
pluggy==1.0.0
py==1.11.0
pycparser==2.21
requests==2.26.0
sgmllib3k==1.0.0
simplebot==2.2.1
simplebot-feeds @ git+https://github.com/simplebot-org/simplebot_feeds@201fff233d7cb161a578ff394f75c1fb399798e6
six==1.16.0
soupsieve==2.3
typing-extensions==3.10.0.2
urllib3==1.26.7
webencodings==0.5.1
zipp==3.6.0
```

**Comment by adbenitez** [comment]
hi, that is weird, seems an issue of python on your system? maybe you can run with `python -m simplebot` and pass additional arguments to python to debug the issue

**Comment by lerdem** [comment]
`-m` flag is not showing additional information. How to run bot debug mode? (Is it possible?)

after running `python -m simplebot --account not_real@mail.com serve` i have got same result as previously.

**Comment by adbenitez** [comment]
flag `-m` is to run the module simplebot, to debug try with `-v` option:

`python -v -m simplebot ....`

**Comment by adbenitez** [comment]
using `-vvv` increase the verbosity level

**Comment by lerdem** [comment]
Verbose is showing nothing.

**Comment by lerdem** [comment]
I have tried to run `simplebot-echo` and get same error. So i think that is not issue of [simplebot_feeds](https://github.com/simplebot-org/simplebot_feeds). It is an issue of [simplebot-org](https://github.com/simplebot-org/simplebot) in general.

**Comment by lerdem** [comment]
The problem was with my system not with simplebot plugin. After changing python version from 3.7.3 to 3.9.8 everything works fine.
