### ISSUE TITLE
Gitea RSS feeds are invalid?

### ISSUE THREAD

**Issue by missytake** [simplebot-org/simplebot_feeds#49]
Hey,

I've been using the feedsbot for a while and now tried to added a git.0x90.space repository to it :) but I got an "invalid feed URL" error.

## Steps to Reproduce

1. send `/sub https://git.0x90.space/missytake/chezmoi-server.rss` to feedsbot@hispanilandia.net

## Possible explanations

- maybe the feedsbot is not happy with .rss as file ending?
- Maybe it's the HTTP `Content-Type | text/xml; charset=utf-8`? e.g. when I open https://subconscious.substack.com/feed in the browser (another feed that works for me), it downloads the xml file instead of opening it in the browser, as with the git.0x90.space RSS link.

**Comment by adbenitez** [comment]
hi, I just tried to send the command you shared to see the error in the logs but it just worked:
![image_2022-08-22_10-06-28](https://user-images.githubusercontent.com/24558636/185896841-2f7d0023-6212-4439-ad99-ea06a6f0f616.jpg)

maybe you was just REALLY unlucky and the bot's PC for some reason had no network access to that gitea server in that exact time? could you retry?

**Comment by missytake** [comment]
ah well no. I just realized, the repository with which I *actually* tried it was a private repository... and of course the bot can't read it :upside_down_face: sorry to bother ŷou^^
